export const BANK_LIST: Record<string, string> = {
  'Access Bank': '044',
  CitiBank: '023',
  'Ecobank Plc': '050',
  'Fidelity Bank': '070',
  'First Bank of Nigeria': '011',
  'First City Monument Bank': '214',
  'Guaranty Trust Bank': '058',
  'Globus Bank': '103',
  'Heritage Bank': '030',
  'Keystone Bank': '082',
  'Lotus Bank': '000029',
  'Optimus Bank': '000036',
  'Parallex Bank': '000030',
  'Polaris Bank': '076',
  'PremiumTrust Bank': '000031',
  'ProvidusBank PLC': '101',
  'SIGNATURE BANK': '000034',
  'Stanbic IBTC Bank': '221',
  'Standard Chartered Bank': '068',
  'Sterling Bank': '232',
  'SunTrust Bank': '100',
  'Taj Bank Limited': '000026',
  'Titan Trust Bank': '000025',
  'Union Bank': '032',
  'United Bank for Africa': '033',
  'Unity Bank': '215',
  'Wema Bank': '035',
  'Zenith Bank': '057',
  'JAIZ Bank': '301',
  Kuda: '090267',
  Opay: '100004',
  PALMPAY: '100033',
  'Moniepoint MFBank': '090405',
  'Eyowo MFB': '090328',
  Sparkle: '090325',
  'Titan-Paystack': '100039',
  eTranzact: '306',
  'Sterling Mobile': '326',
  GTMobile: '315',
  'Fairmoney Microfinance Bank Ltd': '090551',
  'Branch International Financial Services': '050006',
  'Paystack Payments Limited': '110006',
  'Flutterwave Technology Solutions Limited': '110002',
  'Interswitch Limited': '110003',
  TeamApt: '110007',
  Cellulant: '317',
  'PayAttitude Online': '329',
  'Nibssussd Payments': '110019',
  'Xpress Payments': '090201',
  'Smartcash Payment Service Bank': '120004',
};

export const BANK_NAMES = [
  'Access Bank',
  'CitiBank',
  'Ecobank Plc',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank',
  'Guaranty Trust Bank',
  'Globus Bank',
  'Heritage Bank',
  'Keystone Bank',
  'Lotus Bank',
  'Optimus Bank',
  'Parallex Bank',
  'Polaris Bank',
  'PremiumTrust Bank',
  'ProvidusBank PLC',
  'SIGNATURE BANK',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'Taj Bank Limited',
  // 'Titan Trust Bank',
  'Union Bank',
  'United Bank for Africa',
  'Unity Bank',
  'Wema Bank',
  'Zenith Bank',
  'JAIZ Bank',
  'Kuda',
  'Opay',
  'PALMPAY',
  'Moniepoint MFBank',
  'Eyowo MFB',
  'Sparkle',
  'Titan-Paystack',
  'eTranzact',
  'Sterling Mobile',
  'GTMobile',
  'TeamApt',
  'Cellulant',
];
